apiVersion: apps/v1
kind: Deployment
metadata:
  name: py-app
  labels:
    app: py-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: py-app
  template:
    metadata:
      labels:
        app: py-app
    spec:
      containers:
      - name: py-app
        # CHANGE 'YOUR_DOCKER_USERNAME' TO YOUR ACTUAL DOCKER HUB USERNAME
        image: venkatapavank/poc20:76f4bcf6225570d54ef258ed80fc6d18d64d0b28
        ports:
        - containerPort: 8080
