apiVersion: apps/v1
kind: Deployment
metadata:
  name: py-app
  labels:
    app: py-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: py-app
  template:
    metadata:
      labels:
        app: py-app
    spec:
      containers:
      - name: py-app
        # CHANGE 'YOUR_DOCKER_USERNAME' TO YOUR ACTUAL DOCKER HUB USERNAME
        image: venkatapavank/poc20:229ec0a0b745917fa23e5ba95dcb2d07cc625714
        ports:
        - containerPort: 8080
